### ISSUE TITLE
Invalid Field Mapping for OriginalFileName

### ISSUE THREAD

**Issue by otoqui** [7RedViolin/pySigma-backend-sentinelone#1]
First of all, fantastic work on this plugin! Super stoked to finally have a Sigma backend for SentinelOne!

A bug that I noticed when first using it:

The field "OriginalFileName" in Sigma does not map to anything in SentinelOne (to the best of my knowledge there is no 1-to-1 equivalent in SentinelOne's Deep Visibility telemetry), so Sigma rules using it will break the resulting S1 DV query output from sigma-cli.

Taking the same "Suspicious Microsoft OneNote Child Process" Sigma rule used here as an example: https://medium.com/sigma-hq/community-contribution-highlights-sentinelone-joins-pysigma-cedd8825e063 The resulting query cannot be run in Deep Visibility due to the invalid field:
![image](https://user-images.githubusercontent.com/131987202/234929022-5350f08c-3d17-41e5-9738-0fc90511ede3.png)

Again, great work on this plugin so far - looking forward to using it more going forward!

**Comment by 7RedViolin** [comment]
So glad you're finding it useful! I really appreciate the feedback!!
