### ISSUE TITLE
Backends not compatible with sigma-cli v0.7.11

### ISSUE THREAD

**Issue by wikijm** [7RedViolin/pySigma-backend-sentinelone#10]
Hi @7RedViolin

Thanks a lot for what you're doing for Sigma!

Your backends are recognized as not compatible with sigma-cli v0.7.11:
![image](https://github.com/7RedViolin/pySigma-backend-sentinelone/assets/10724809/bf9d8ba4-70c4-4663-9074-857794dc8082)

As I'm new with sigma-cli, I'm assuming I probably missed something.
Do we have to do more than executing `pip3 install pysigma-backend-sentinelone` and `pip3 install pysigma-backend-sentinelone-pq` to get the latest plugin versions?

Result of install is:
![image](https://github.com/7RedViolin/pySigma-backend-sentinelone/assets/10724809/a2c98121-ac6c-4762-8b30-875a9dff51f1)

Regards,
WikiJM

**Comment by 7RedViolin** [comment]
Hey @wikijm ! Digging into this, I think this can be resolved in this PR: https://github.com/SigmaHQ/pySigma-plugin-directory/pull/29 but will keep this issue open until that PR is merged and I have a chance to test and verify the fix

**Comment by wikijm** [comment]
Thanks a lot!
