### ISSUE TITLE
issue converting sigma rules

### ISSUE THREAD

**Issue by YohanesDTech** [7RedViolin/pySigma-backend-sentinelone#8]
New to Sentinelone Simga plugin, having a field issue on the conversion of the sigma rule. I used the rule that was listed on the README documentation.

 "sigma convert -t sentinelone proc_creation_win_office_onenote_susp_child_processes.yml 

/Sigma/myvenv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Parsing Sigma rules  [####################################]  100%
Error while conversion: Invalid SigmaDetectionItem field name encountered: OriginalFileName. This pipeline only supports the following fields:
{CommandLine}, {Company}, {CurrentDirectory}, {Description}, {DestinationHostname}, {DestinationIp}, {DestinationPort}, {Details}, {DnsRequest}, {DnsResponse}, {DstIP}, {DstPort}, {EventType}, {Image}, {ImageLoaded}, {IntegrityLevel}, {ModuleMd5}, {ModulePath}, {ModuleSha1}, {NamedPipeName}, {NetProtocolName}, {ObjectType}, {ParentCommandLine}, {ParentImage}, {ParentProcessId}, {PipeName}, {ProcessId}, {Product}, {Protocol}, {QueryName}, {RegistryKeyPath}, {RegistryValue}, {SourceFilename}, {SourceIp}, {SourcePort}, {SrcIP}, {SrcPort}, {SrcProcCmdLine}, {SrcProcImagePath}, {SrcProcPID}, {SrcProcParentCmdline}, {SrcProcParentImagePath}, {SrcProcUser}, {TargetFilename}, {TargetObject}, {TerminalSessionId}, {TgtFileOldPath}, {TgtFilePath}, {TgtProcCmdLine}, {TgtProcDisplayName}, {TgtProcImagePath}, {TgtProcIntegrityLevel}, {TgtProcMd5}, {TgtProcPID}, {TgtProcPublisher}, {TgtProcSessionId}, {TgtProcSha1}, {TgtProcSha256}, {TgtProcUser}, {Url}, {User}, {answer}, {dst_ip}, {dst_port}, {md5}, {query}, {record_type}, {sha1}, {sha256}, {src_ip}, {src_port"

**Comment by 7RedViolin** [comment]
Hi @YohanesDTech ! The documentation needs to be updated - the field `OriginalFileName` currently isn't supported as I don't believe there is a clear mapping to a SentinelOne native field. However, if you have a recommendation, let me know and I can test it and potentially added to this backend/pipeline
